name: pipeline
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - 'main'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push Go
        id: build-push-server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-server
          push: true
          tags: correba/iziclock_server:latest

      - name: build and push nginx
        id: build-push-reverse
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-reverse
          push: true
          tags: correba/iziclock_reverse:latest
